version: '3.9'

services:
  gdmp-authorization:
    build: .
    container_name: $CONTAINER_NAME
    image: $IMAGE_NAME
    command: sh ./script.sh
    env_file:
      - .env
    volumes: 
      - .:/app
    ports:
      - $SERVER_PORT:$SERVER_PORT
    networks:
      - eval-network

networks:
  eval-network:
    external: true
